name: Fetch Meta Ads Batch

on:
  workflow_dispatch:  # 手動でのみ実行

jobs:
  run-batch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Write credentials.json from Secret
        run: echo "${{ secrets.GSHEET_JSON_BASE64 }}" | base64 -d > credentials.json

      - name: Run batch script
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GSHEET_JSON_BASE64: ${{ secrets.GSHEET_JSON_BASE64 }}
        run: python main_batch.py
