name: Fetch Meta Ads Report

on:
  schedule:
    - cron: '0 21 * * *'  # JST 毎朝6:00
  workflow_dispatch:

jobs:
  fetch-and-write:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create credentials.json from secret
        run: echo "${{ secrets.GSHEET_JSON_BASE64 }}" | base64 -d > credentials.json

      - name: Run main script
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GSHEET_JSON_BASE64: ${{ secrets.GSHEET_JSON_BASE64 }}
        run: python main_daily.py
