name: Fetch Meta Ads Report

on:
  schedule:
    - cron: '0 21 * * *'  # 毎日 6:00 JST（UTCで21:00）
  workflow_dispatch:       # 手動実行も可

jobs:
  fetch-and-write:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create credentials.json from secret
        run: echo "${{ secrets.GSHEET_JSON }}" > credentials.json

      - name: Run main script
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          python main.py
